name: Build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: centos:8
    steps:
      - name: pwd
        run: echo $(pwd)
      - name: checkout
        uses: actions/checkout@v2
      - name: pwd
        run: echo $(pwd)
      - name: ls
        run: ls -lah
